apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "printenv" ]
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: credentials
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: credentials
              key: password
  restartPolicy: Never