apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  containers:
  - name: tomcat
    image: tomcat:alpine
    ports:
    - containerPort: 9090
    readinessProbe:
      tcpSocket:
        port: 9090
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 9090
      initialDelaySeconds: 15
      periodSeconds: 20
    volumeMounts:
      - name: tomcat-server-xml-conf-volume
        mountPath: /usr/local/tomcat/conf/server.xml
        subPath: server.xml
  volumes:
    - name: tomcat-server-xml-conf-volume
      configMap:
        name: tomcat-server-xml-conf