apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        # versions: 8-slim, 9-slim
        image: tomcat:8-slim
        ports:
        - containerPort: 8080
          protocol: TCP
